DEFINE DYNAMIC TABLE TEMP.NARUMUGAM.CUSTOMERS_CLEAN
    TARGET_LAG = '5 minutes'
    WAREHOUSE = SNOWADHOC
AS
SELECT 
    CUSTOMER_ID,
    TRIM(UPPER(CUSTOMER_NAME)) AS CUSTOMER_NAME,
    LOWER(TRIM(EMAIL)) AS EMAIL,
    UPPER(REGION) AS REGION,
    CREATED_AT,
    UPDATED_AT
FROM TEMP.NARUMUGAM.CUSTOMERS
WHERE CUSTOMER_ID IS NOT NULL;

DEFINE DYNAMIC TABLE TEMP.NARUMUGAM.CUSTOMER_ORDERS_SUMMARY
    TARGET_LAG = '1 hour'
    WAREHOUSE = SNOWADHOC
AS
SELECT 
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.REGION,
    COUNT(o.ORDER_ID) AS TOTAL_ORDERS,
    SUM(o.ORDER_AMOUNT) AS TOTAL_REVENUE,
    AVG(o.ORDER_AMOUNT) AS AVG_ORDER_VALUE,
    MAX(o.ORDER_DATE) AS LAST_ORDER_DATE
FROM TEMP.NARUMUGAM.CUSTOMERS_CLEAN c
LEFT JOIN TEMP.NARUMUGAM.ORDERS o 
    ON c.CUSTOMER_ID = o.CUSTOMER_ID
GROUP BY c.CUSTOMER_ID, c.CUSTOMER_NAME, c.REGION;
