-- Dynamic Tables for automated data pipeline
-- Bronze -> Silver -> Gold medallion architecture

-- BRONZE LAYER: Cleaned raw data (1 minute lag)
CREATE OR REPLACE DYNAMIC TABLE DEMO_INGEST_DB.BRONZE.ORDERS_CLEANED
    TARGET_LAG = '1 minute'
    WAREHOUSE = COMPUTE_WH
AS
SELECT 
    ORDER_ID,
    CUSTOMER_ID,
    TRY_TO_DATE(ORDER_DATE) as ORDER_DATE,
    TRY_TO_DECIMAL(ORDER_AMOUNT, 18, 2) as ORDER_AMOUNT,
    UPPER(TRIM(STATUS)) as STATUS,
    LOAD_TIMESTAMP,
    CURRENT_TIMESTAMP() as PROCESSED_TIMESTAMP
FROM DEMO_INGEST_DB.RAW.ORDERS_RAW
WHERE ORDER_ID IS NOT NULL;

CREATE OR REPLACE DYNAMIC TABLE DEMO_INGEST_DB.BRONZE.CUSTOMERS_CLEANED
    TARGET_LAG = '1 minute'
    WAREHOUSE = COMPUTE_WH
AS
SELECT 
    CUSTOMER_ID,
    TRIM(CUSTOMER_NAME) as CUSTOMER_NAME,
    UPPER(TRIM(REGION)) as REGION,
    UPPER(TRIM(SEGMENT)) as SEGMENT,
    LOAD_TIMESTAMP,
    CURRENT_TIMESTAMP() as PROCESSED_TIMESTAMP
FROM DEMO_INGEST_DB.RAW.CUSTOMERS_RAW
WHERE CUSTOMER_ID IS NOT NULL;

-- SILVER LAYER: Enriched data with joins (5 minute lag)
CREATE OR REPLACE DYNAMIC TABLE DEMO_INGEST_DB.SILVER.ORDERS_ENRICHED
    TARGET_LAG = '5 minutes'
    WAREHOUSE = COMPUTE_WH
AS
SELECT 
    o.ORDER_ID,
    o.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.REGION,
    c.SEGMENT,
    o.ORDER_DATE,
    o.ORDER_AMOUNT,
    o.STATUS,
    o.PROCESSED_TIMESTAMP as ORDER_PROCESSED_AT,
    CURRENT_TIMESTAMP() as ENRICHED_AT
FROM DEMO_INGEST_DB.BRONZE.ORDERS_CLEANED o
LEFT JOIN DEMO_INGEST_DB.BRONZE.CUSTOMERS_CLEANED c 
    ON o.CUSTOMER_ID = c.CUSTOMER_ID;

-- GOLD LAYER: Aggregated for reporting (1 hour lag)
CREATE OR REPLACE DYNAMIC TABLE DEMO_INGEST_DB.GOLD.DAILY_SALES_SUMMARY
    TARGET_LAG = '1 hour'
    WAREHOUSE = COMPUTE_WH
AS
SELECT 
    ORDER_DATE,
    REGION,
    SEGMENT,
    COUNT(DISTINCT ORDER_ID) as ORDER_COUNT,
    COUNT(DISTINCT CUSTOMER_ID) as CUSTOMER_COUNT,
    SUM(ORDER_AMOUNT) as TOTAL_REVENUE,
    AVG(ORDER_AMOUNT) as AVG_ORDER_VALUE,
    COUNT(CASE WHEN STATUS = 'COMPLETED' THEN 1 END) as COMPLETED_ORDERS,
    COUNT(CASE WHEN STATUS = 'PENDING' THEN 1 END) as PENDING_ORDERS,
    CURRENT_TIMESTAMP() as REFRESHED_AT
FROM DEMO_INGEST_DB.SILVER.ORDERS_ENRICHED
GROUP BY ORDER_DATE, REGION, SEGMENT;
