-- Dynamic Tables for Analytics Pipeline
-- Managed via GitLab CI/CD

CREATE OR REPLACE DYNAMIC TABLE ANALYTICS_DEV.STAGING.CUSTOMERS_CLEAN
    TARGET_LAG = '5 minutes'
    WAREHOUSE = ANALYTICS_WH_DEV
AS
SELECT 
    CUSTOMER_ID,
    TRIM(UPPER(CUSTOMER_NAME)) AS CUSTOMER_NAME,
    LOWER(TRIM(EMAIL)) AS EMAIL,
    UPPER(REGION) AS REGION,
    CREATED_AT,
    UPDATED_AT
FROM ANALYTICS_DEV.RAW.CUSTOMERS
WHERE CUSTOMER_ID IS NOT NULL;

CREATE OR REPLACE DYNAMIC TABLE ANALYTICS_DEV.MARTS.CUSTOMER_ORDERS_SUMMARY
    TARGET_LAG = '1 hour'
    WAREHOUSE = ANALYTICS_WH_DEV
AS
SELECT 
    c.CUSTOMER_ID,
    c.CUSTOMER_NAME,
    c.REGION,
    COUNT(o.ORDER_ID) AS TOTAL_ORDERS,
    SUM(o.ORDER_AMOUNT) AS TOTAL_REVENUE,
    AVG(o.ORDER_AMOUNT) AS AVG_ORDER_VALUE,
    MAX(o.ORDER_DATE) AS LAST_ORDER_DATE
FROM ANALYTICS_DEV.STAGING.CUSTOMERS_CLEAN c
LEFT JOIN ANALYTICS_DEV.RAW.ORDERS o 
    ON c.CUSTOMER_ID = o.CUSTOMER_ID
GROUP BY c.CUSTOMER_ID, c.CUSTOMER_NAME, c.REGION;
