-- Infrastructure setup for Serverless Migration Demo
-- Managed via GitHub Actions CI/CD

-- Create database and schemas
CREATE DATABASE IF NOT EXISTS DEMO_INGEST_DB;
CREATE SCHEMA IF NOT EXISTS DEMO_INGEST_DB.RAW;
CREATE SCHEMA IF NOT EXISTS DEMO_INGEST_DB.BRONZE;
CREATE SCHEMA IF NOT EXISTS DEMO_INGEST_DB.SILVER;
CREATE SCHEMA IF NOT EXISTS DEMO_INGEST_DB.GOLD;

-- File formats
CREATE OR REPLACE FILE FORMAT DEMO_INGEST_DB.RAW.CSV_FORMAT
    TYPE = 'CSV'
    FIELD_DELIMITER = ','
    SKIP_HEADER = 1
    NULL_IF = ('NULL', 'null', '')
    EMPTY_FIELD_AS_NULL = TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    COMPRESSION = AUTO;

CREATE OR REPLACE FILE FORMAT DEMO_INGEST_DB.RAW.JSON_FORMAT
    TYPE = 'JSON'
    COMPRESSION = AUTO
    STRIP_OUTER_ARRAY = TRUE;

-- Internal stage for demo
CREATE OR REPLACE STAGE DEMO_INGEST_DB.RAW.INTERNAL_STAGE
    FILE_FORMAT = DEMO_INGEST_DB.RAW.CSV_FORMAT;

-- Source tables with change tracking enabled
CREATE TABLE IF NOT EXISTS DEMO_INGEST_DB.RAW.ORDERS_RAW (
    ORDER_ID VARCHAR(50),
    CUSTOMER_ID VARCHAR(50),
    ORDER_DATE VARCHAR(50),
    ORDER_AMOUNT VARCHAR(50),
    STATUS VARCHAR(50),
    LOAD_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
)
CHANGE_TRACKING = TRUE;

CREATE TABLE IF NOT EXISTS DEMO_INGEST_DB.RAW.CUSTOMERS_RAW (
    CUSTOMER_ID VARCHAR(50),
    CUSTOMER_NAME VARCHAR(200),
    REGION VARCHAR(50),
    SEGMENT VARCHAR(50),
    LOAD_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
)
CHANGE_TRACKING = TRUE;

-- Customer events table for Snowpipe
CREATE TABLE IF NOT EXISTS DEMO_INGEST_DB.RAW.CUSTOMER_EVENTS (
    EVENT_ID VARCHAR(50),
    CUSTOMER_ID VARCHAR(50),
    EVENT_TYPE VARCHAR(100),
    EVENT_TIMESTAMP TIMESTAMP,
    EVENT_DATA VARIANT,
    FILE_NAME VARCHAR(500),
    LOAD_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

-- Incremental processing target
CREATE TABLE IF NOT EXISTS DEMO_INGEST_DB.SILVER.ORDERS_INCREMENTAL (
    ORDER_ID VARCHAR(50),
    CUSTOMER_ID VARCHAR(50),
    ORDER_DATE DATE,
    ORDER_AMOUNT DECIMAL(18,2),
    STATUS VARCHAR(50),
    CHANGE_TYPE VARCHAR(20),
    PROCESSED_TIMESTAMP TIMESTAMP
);

-- Sample data
MERGE INTO DEMO_INGEST_DB.RAW.CUSTOMERS_RAW t
USING (
    SELECT 'C001' as CUSTOMER_ID, 'Acme Corp' as CUSTOMER_NAME, 'WEST' as REGION, 'ENTERPRISE' as SEGMENT
    UNION ALL SELECT 'C002', 'Beta Inc', 'EAST', 'SMB'
    UNION ALL SELECT 'C003', 'Gamma LLC', 'CENTRAL', 'ENTERPRISE'
) s ON t.CUSTOMER_ID = s.CUSTOMER_ID
WHEN NOT MATCHED THEN INSERT (CUSTOMER_ID, CUSTOMER_NAME, REGION, SEGMENT) VALUES (s.CUSTOMER_ID, s.CUSTOMER_NAME, s.REGION, s.SEGMENT);

MERGE INTO DEMO_INGEST_DB.RAW.ORDERS_RAW t
USING (
    SELECT 'ORD001' as ORDER_ID, 'C001' as CUSTOMER_ID, '2025-01-15' as ORDER_DATE, '150.00' as ORDER_AMOUNT, 'COMPLETED' as STATUS
    UNION ALL SELECT 'ORD002', 'C002', '2025-01-16', '250.00', 'PENDING'
    UNION ALL SELECT 'ORD003', 'C001', '2025-01-17', '75.50', 'COMPLETED'
    UNION ALL SELECT 'ORD004', 'C003', '2025-01-18', '500.00', 'SHIPPED'
) s ON t.ORDER_ID = s.ORDER_ID
WHEN NOT MATCHED THEN INSERT (ORDER_ID, CUSTOMER_ID, ORDER_DATE, ORDER_AMOUNT, STATUS) VALUES (s.ORDER_ID, s.CUSTOMER_ID, s.ORDER_DATE, s.ORDER_AMOUNT, s.STATUS);
