-- Tasks for scheduled and event-driven processing

-- Serverless task for data cleanup (no warehouse specified)
CREATE OR REPLACE TASK DEMO_INGEST_DB.RAW.CLEANUP_OLD_DATA_SERVERLESS
    SCHEDULE = 'USING CRON 0 2 * * * America/New_York'
    USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
    COMMENT = 'Serverless task to clean up staging data older than 7 days'
AS
    DELETE FROM DEMO_INGEST_DB.RAW.ORDERS_RAW
    WHERE LOAD_TIMESTAMP < DATEADD(day, -7, CURRENT_TIMESTAMP());

-- Stream-triggered task for incremental processing
CREATE OR REPLACE TASK DEMO_INGEST_DB.RAW.PROCESS_ORDERS_STREAM
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '1 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('DEMO_INGEST_DB.RAW.ORDERS_STREAM')
    COMMENT = 'Processes order changes incrementally'
AS
    INSERT INTO DEMO_INGEST_DB.SILVER.ORDERS_INCREMENTAL
    SELECT 
        ORDER_ID,
        CUSTOMER_ID,
        TRY_TO_DATE(ORDER_DATE),
        TRY_TO_DECIMAL(ORDER_AMOUNT, 18, 2),
        STATUS,
        CASE 
            WHEN METADATA$ACTION = 'INSERT' THEN 'INSERT'
            WHEN METADATA$ACTION = 'DELETE' AND METADATA$ISUPDATE = TRUE THEN 'UPDATE'
            WHEN METADATA$ACTION = 'DELETE' THEN 'DELETE'
        END as CHANGE_TYPE,
        CURRENT_TIMESTAMP()
    FROM DEMO_INGEST_DB.RAW.ORDERS_STREAM;

-- Data quality check task
CREATE OR REPLACE TASK DEMO_INGEST_DB.RAW.DATA_QUALITY_CHECK
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = 'USING CRON 0 6 * * * America/New_York'
    COMMENT = 'Daily data quality validation'
AS
    INSERT INTO DEMO_INGEST_DB.RAW.DATA_QUALITY_LOG
    SELECT 
        CURRENT_TIMESTAMP() as CHECK_TIME,
        'ORDERS_RAW' as TABLE_NAME,
        COUNT(*) as TOTAL_ROWS,
        COUNT(CASE WHEN ORDER_ID IS NULL THEN 1 END) as NULL_ORDER_IDS,
        COUNT(CASE WHEN TRY_TO_DATE(ORDER_DATE) IS NULL AND ORDER_DATE IS NOT NULL THEN 1 END) as INVALID_DATES,
        COUNT(CASE WHEN TRY_TO_DECIMAL(ORDER_AMOUNT, 18, 2) IS NULL AND ORDER_AMOUNT IS NOT NULL THEN 1 END) as INVALID_AMOUNTS
    FROM DEMO_INGEST_DB.RAW.ORDERS_RAW;
